name: Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'

      - uses: actions/checkout@v2
      - name: Validation
        run: |
          pod lib lint --allow-warnings
