name: Publish iOS

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cocoapods-release:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./ios
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: CocoaPods Release
        with:
          ref: main
        run: pod trunk push Qonversion.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
