name: Upgrade cross-platforms on release

on:
  workflow_run:
    workflows: [Publish SDKs]
    types:
      - completed

jobs:
  notify_cross_platforms:
    name: Wait for publishing and upgrade cross-platforms
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Previous tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Notify cross-platforms
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'qonversion',
              repo: 'react-native-sdk',
              workflow_id: 'upgrade_sandwich.yml',
              ref: 'main',
              inputs: {
                sandwich_version: '${{ steps.current_tag.outputs.tag }}'
              },
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'qonversion',
              repo: 'flutter-sdk',
              workflow_id: 'upgrade_sandwich.yml',
              ref: 'main',
              inputs: {
                sandwich_version: '${{ steps.current_tag.outputs.tag }}'
              },
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'qonversion',
              repo: 'unity-sdk',
              workflow_id: 'upgrade_sandwich.yml',
              ref: 'main',
              inputs: {
                sandwich_version: '${{ steps.current_tag.outputs.tag }}'
              },
            })
  on_publishing_failed:
    name: Cancel due to publishing faulure
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    uses: actions/github-script@v3
    with:
      script: |
          core.setFailed('Publishing script failed')
